import { Resource } from "../types/resource";

/** randomly generated by ChatGPT */
function getNameList() {
    const names = [
        "James",
        "Mary",
        "John",
        "Patricia",
        "Robert",
        "Jennifer",
        "Michael",
        "Linda",
        "William",
        "Elizabeth",
        "David",
        "Barbara",
        "Richard",
        "Susan",
        "Joseph",
        "Jessica",
        "Thomas",
        "Sarah",
        "Charles",
        "Karen",
        "Christopher",
        "Nancy",
        "Daniel",
        "Lisa",
        "Matthew",
        "Betty",
        "Anthony",
        "Margaret",
        "Mark",
        "Sandra",
    ];
    for (let i = names.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [names[i], names[j]] = [names[j], names[i]];
    }
    return names;
}

function* classRoomStudentCreator(): Generator<
    Resource.ClassRoom.Student,
    void,
    void
> {
    for (const [index, name] of getNameList().entries()) {
        yield {
            groupId: 0,
            seatNumber: index + 1,
            score: 0,
            // simulate some seats are empty
            student:
                Math.random() > 0.3
                    ? {
                          id: `stu-${index + 1}`,
                          name: name,
                      }
                    : undefined,
        };
    }
}

export const classRoomStudents = Array.from(classRoomStudentCreator());

export const classRoom: Resource.ClassRoom.ClassRoom = {
    id: "X58E9647",
    name: "302 Science",
};
